# Generated by Django 4.2.24 on 2026-03-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_post_blog', 'Can post blog posts')]},
        ),
        migrations.AlterField(
            model_name='profile',
            name='can_post_blog',
            field=models.BooleanField(default=False, help_text='Can post blog posts'),
        ),
    ]
