# Generated by Django 6.0.2 on 2026-04-30 19:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accessibility_details',
            field=models.TextField(blank=True, help_text='Describe how this event is accessible. If left blank, event is not marked as accessible.'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendee_list_public',
            field=models.BooleanField(default=True, help_text='If false, only organizers can see the attendee list.'),
        ),
        migrations.AddField(
            model_name='event',
            name='enable_rsvp_questions',
            field=models.BooleanField(default=False, help_text='Enable optional RSVP questions for this event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='question1_text',
            field=models.CharField(blank=True, default='', help_text='Custom text for RSVP Question 1. Leave blank for default.', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='question2_text',
            field=models.CharField(blank=True, default='', help_text='Custom text for RSVP Question 2. Leave blank for default.', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='question3_text',
            field=models.CharField(blank=True, default='', help_text='Custom text for RSVP Question 3. Leave blank for default.', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='telegram_webhook_channel',
            field=models.CharField(blank=True, help_text='Telegram channel name for webhook posting (without @)', max_length=100, null=True, verbose_name='Telegram Webhook Channel (without @)'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='question1',
            field=models.CharField(blank=True, help_text='Organizer-only question 1 (visible only to event organizers)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='question2',
            field=models.CharField(blank=True, help_text='Organizer-only question 2 (visible only to event organizers)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='question3',
            field=models.CharField(blank=True, help_text='Organizer-only question 3 (visible only to event organizers)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum number of attendees. Leave blank for no limit.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
