# Generated by Django 6.0.2 on 2026-04-30 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_accessibility_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha_2_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('alpha_3_code', models.CharField(blank=True, max_length=3, null=True, unique=True)),
                ('country_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='events.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['country__alpha_2_code', 'state_name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(blank=True, help_text='IANA time zone for the event location', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.state', db_column='state_id'),
        ),
    ]
