# Generated by Django 4.2.24 on 2026-03-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_accessibility_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='accessibility_needs',
            field=models.BooleanField(default=False, help_text='Show accessibility indicator on badge'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='custom_rank',
            field=models.CharField(blank=True, help_text="Custom rank/role label for badge (e.g. 'Sponsor', 'VIP', 'Staff')", max_length=50, null=True),
        ),
    ]
